parameters:
  datalake:
    base_path: '/foo/bar'

  datalakebundle:
    table:
      name_template: '%kernel.environment%_{identifier}'
      defaults:
        encrypted: !expr 'db_identifier[-1:] == "e"'
        db_identifier_base: !expr 'db_identifier[:db_identifier.find("_")]'
        target_path:
          resolver_class: 'datalakebundle.test.TargetPathResolver'
          resolver_arguments:
            - '%datalake.base_path%'
    filesystem: dummy_filesystem

  # backward compatibility, will be removed in 2.0
  pysparkbundle:
    filesystem: "%datalakebundle.filesystem%"
    dataframe:
      show_method:

services:
  datalakebundle.test.DummySparkFactory:

  pyspark.sql.session.SparkSession:
    factory: ['@datalakebundle.test.DummySparkFactory', 'create']

  datalakebundle.filesystem.DummyFilesystem:
    tags:
      - {name: 'datalakebundle.filesystem', alias: dummy_filesystem}
      - {name: 'pysparkbundle.filesystem', alias: dummy_filesystem} # backward compatibility, will be removed in 2.0
